### ISSUE TITLE
Is "mergedConfiguration" the intended property name in the useExtensionInfo hook?

### ISSUE THREAD

**Issue by kishba** [ellucian-developer/experience-extension-hooks#9]
I'm sorry for not trying this change earlier, but I am finally trying out the merged card/page configuration in one of my child components. I'm getting an error that `configuration` is undefined when I use this code from the README:

```javascript
const { basePath, configuration, extensionId, type } = useExtensionInfo();
```

Here are the first few lines of the error in my browser console (with the unadvertised `devSharedModules` mode enabled):
```
error: message: configuration is undefined stack:
ChildComponent@webpack-internal:///./src/components/ChildComponent.jsx:43:23
...
```

When I use the React dev tools, it looks like this property is named `mergedConfiguration` rather than `configuration`. Is this intended?

![2021-08-11-extensionInfo-mergedConfiguration-vs-configuration](https://user-images.githubusercontent.com/11190/129065846-afee481b-eafb-423f-9406-807e45c92478.png)

If this is the intended name, I think a README update is in order. For now, I'm using this to rename the property:

```javascript
  const { mergedConfiguration: configuration } = useExtensionInfo();
```

Thanks,
Brandon

**Comment by ellucianBret** [comment]
I mused on this for a bit, but not long enough.

From a page, you have access to useExtensionInfo().mergedConfiguration and useCardInfo().cardConfiguration. I intended the mergedConfiguration to be clear that it was card level configuration and extension level configuration, but it is not.

I think you asked for an already "merged" configuration so that as a Page developer you wouldn't have to combine.
I am thinking it is more confusing with it merged. 

I am thinking for clarity it should just be useExtensionInfo().configuration for extension level config and useCardInfo().cardConfiguration for card level configuration. In the use cases where you need to combine, it is straight forward to do something like:

`const combinedConfiguration = {... extensionConfiguration, ... cardConfiguration };`

This hooks package could proffer a combinedConfiguration, but it is not clear where it would make sense to put it :)

Of course, the downside to this is that in a Card, there is only one configuration offered, and it combines extension and card configuration.

I will move back to a working extension info with extension configuration and card info with card configuration for a Page for now.

Thoughts?

Bret

**Comment by kishba** [comment]
Yeah, it is a little confusing and it may be too bold to make a new convention that doesn't originate from the SDK.

I'm going to try your proposed merge syntax and see how it feels in practice. I'll try to provide more feedback in the next day or two.

Thank you again for sharing these hooks!

**Comment by kishba** [comment]
Here's a real life example from a component I'm sharing between a page and card with a comment included to explain to my co-developers why I'm doing this:

```javascript
  // Cards will have card + extension configuration values merged already,
  // but for compatibility on pages, we need to combine them ourselves
  const { configuration: extensionConfiguration } = useExtensionInfo();
  const { configuration: cardConfiguration } = useCardInfo();
  const combinedConfiguration = {
    ...extensionConfiguration,
    ...cardConfiguration
  };
  const selfServiceBaseURL =
    combinedConfiguration.extensionSelfServiceBaseURL ||
    "https://self-service.schoolcraft.edu/Student";
```

I think this is manageable. Will you be promoting/explaining this pattern in the README?

**Comment by ellucianBret** [comment]
I have pushed a new 1.0.5 version which should work as you posted above. For Pages both useExtensionInfo and useCardInfo proffer a configuration.

I will let you close this issue after you test it.

Wishing there was something like Slack that allowed more real-time collaboration with you all :)

**Comment by kishba** [comment]
Gosh, I didn't realize my approach wasn't working for accessing card-only configuration values on pages since the particular card that linked to my page didn't have a card-only configuration value. Thank you for preemptively fixing that for me. :)

**Comment by kishba** [comment]
I tested release `1.0.5` and was able to access the card-only configuration from my page component using `useCardInfo().configuration`. I'm glad we talked about this even if it wasn't real-time! :)

Here's a screenshot of my self-induced bug that was fixed after installing the release and refreshing:
![2021-08-13-useCardInfo-configuration](https://user-images.githubusercontent.com/11190/129355014-a7784efe-cc56-4265-bf6f-354dc462bcc5.png)

Despite having been on the SDK team *and* reading the Experience SDK documentation multiple times, I still haven't internalized the subtle naming difference between cards and pages accessing configuration. I see now that it subtly hints that the configuration values aren't merged when you're on a page, but I keep mixing this up!

Card:
```
props.cardInfo.configuration
```

Page:
```
props.cardInfo.cardConfiguration
```

If I ever build a time machine I might try to stop the configuration merging behavior on cards. :)
